name: Test deployment
on:
  pull_request:
    branches: [ "release" ]
    types: [closed]

jobs:
  my-action:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Reset develop branch
        run: |
          git fetch origin release:release
          git reset --hard release
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: master-promotion